name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main
        run: git merge upstream/main

      - name: Push changes to origin
        run: git push origin main
